version: "3.7"
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
      MYSQL_DATABASE: test
    volumes:
      - ./tests/config/mysql_init.sh:/docker-entrypoint-initdb.d/mysql_init.sh
  postresql:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./tests/config/postgres_init.sh:/docker-entrypoint-initdb.d/postgres_init.sh
    environment:
      POSTGRES_USER: scott
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: test
      POSTGRES_INIT_DB_ARGS: -E 'UTF-8'

